from datetime import datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import Numeric, DateTime, ForeignKey, String, Index, Text, CheckConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.core.enums import SignalType, SignalStatus


class Signal(Base):
    """
    Represents AI-generated trading signals based on event analysis.

    Signals are actionable insights generated by analyzing the correlation
    between geopolitical events and market movements.
    """

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)

    # Foreign keys
    event_id: Mapped[int] = mapped_column(ForeignKey("events.id", ondelete="CASCADE"), nullable=False)
    event = relationship("Event", back_populates="signals")

    entity_id: Mapped[int] = mapped_column(ForeignKey("entities.id", ondelete="CASCADE"), nullable=False)
    entity = relationship("Entity", back_populates="signals")

    # Signal details — values constrained by CheckConstraint + StrEnum
    signal_type: Mapped[str] = mapped_column(String(50), nullable=False)
    confidence: Mapped[Decimal] = mapped_column(Numeric(3, 2), nullable=False)  # 0.00 to 1.00

    # Price targets and recommendation
    target_price: Mapped[Optional[Decimal]] = mapped_column(Numeric(12, 2), nullable=True)
    stop_loss: Mapped[Optional[Decimal]] = mapped_column(Numeric(12, 2), nullable=True)

    # Reasoning
    reasoning: Mapped[str] = mapped_column(Text, nullable=False)

    # Signal status
    status: Mapped[str] = mapped_column(String(20), nullable=False, default=SignalStatus.ACTIVE)

    # Performance tracking
    entry_price: Mapped[Optional[Decimal]] = mapped_column(Numeric(12, 2), nullable=True)
    exit_price: Mapped[Optional[Decimal]] = mapped_column(Numeric(12, 2), nullable=True)
    pnl_percent: Mapped[Optional[Decimal]] = mapped_column(Numeric(8, 2), nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    closed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    _signal_type_values = ", ".join(f"'{v}'" for v in SignalType)
    _status_values = ", ".join(f"'{v}'" for v in SignalStatus)

    __table_args__ = (
        CheckConstraint(f"signal_type IN ({_signal_type_values})", name="ck_signals_signal_type"),
        CheckConstraint(f"status IN ({_status_values})", name="ck_signals_status"),
        CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_signals_confidence_range"),
        Index("ix_signals_event_id", "event_id"),
        Index("ix_signals_entity_id", "entity_id"),
        Index("ix_signals_signal_type", "signal_type"),
        Index("ix_signals_status", "status"),
        Index("ix_signals_confidence", "confidence"),
        Index("ix_signals_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<Signal(id={self.id}, event_id={self.event_id}, signal_type={self.signal_type}, confidence={self.confidence})>"
