"""Backtesting engine for signal validation."""

import logging
from datetime import datetime
from typing import Optional

from app.geopolitical.models import SignalResult
from app.geopolitical.signals import generate_signal

logger = logging.getLogger(__name__)


class BacktestTrade:
    """A single trade generated by a signal."""

    def __init__(
        self,
        signal: SignalResult,
        entry_price: float,
        entry_date: datetime,
        exit_price: Optional[float] = None,
        exit_date: Optional[datetime] = None,
    ):
        self.signal = signal
        self.entry_price = entry_price
        self.entry_date = entry_date
        self.exit_price = exit_price
        self.exit_date = exit_date
        self.pnl_pct: Optional[float] = None

    def close(self, exit_price: float, exit_date: datetime) -> None:
        self.exit_price = exit_price
        self.exit_date = exit_date
        if self.signal.action == "BUY":
            self.pnl_pct = (exit_price - self.entry_price) / self.entry_price
        elif self.signal.action == "SELL":
            self.pnl_pct = (self.entry_price - exit_price) / self.entry_price
        elif self.signal.action == "SHORT":
            self.pnl_pct = (self.entry_price - exit_price) / self.entry_price
        else:  # HOLD
            self.pnl_pct = 0.0


class BacktestResult:
    """Aggregated results from a backtest run."""

    def __init__(self):
        self.trades: list[BacktestTrade] = []
        self.total_trades = 0
        self.winning_trades = 0
        self.losing_trades = 0
        self.total_pnl_pct = 0.0
        self.max_drawdown = 0.0
        self.sharpe_ratio = 0.0
        self.win_rate = 0.0
        self.avg_win = 0.0
        self.avg_loss = 0.0
        self.profit_factor = 0.0

    def calculate(self) -> None:
        self.total_trades = len(self.trades)
        if self.total_trades == 0:
            return

        wins = [t.pnl_pct for t in self.trades if t.pnl_pct and t.pnl_pct > 0]
        losses = [t.pnl_pct for t in self.trades if t.pnl_pct and t.pnl_pct <= 0]

        self.winning_trades = len(wins)
        self.losing_trades = len(losses)
        self.win_rate = self.winning_trades / self.total_trades if self.total_trades > 0 else 0.0
        self.total_pnl_pct = sum(t.pnl_pct or 0.0 for t in self.trades)
        self.avg_win = sum(wins) / len(wins) if wins else 0.0
        self.avg_loss = sum(losses) / len(losses) if losses else 0.0

        gross_profit = sum(wins) if wins else 0.0
        gross_loss = abs(sum(losses)) if losses else 1.0
        self.profit_factor = gross_profit / gross_loss if gross_loss != 0 else 0.0

        # Calculate Sharpe ratio (simplified, assuming daily returns)
        returns = [t.pnl_pct or 0.0 for t in self.trades]
        if len(returns) > 1:
            avg_return = sum(returns) / len(returns)
            std_return = (sum((r - avg_return) ** 2 for r in returns) / len(returns)) ** 0.5
            self.sharpe_ratio = (avg_return / std_return * (252 ** 0.5)) if std_return > 0 else 0.0

        # Max drawdown
        cumulative = 0.0
        peak = 0.0
        for t in self.trades:
            cumulative += t.pnl_pct or 0.0
            if cumulative > peak:
                peak = cumulative
            drawdown = peak - cumulative
            if drawdown > self.max_drawdown:
                self.max_drawdown = drawdown

    def summary(self) -> dict:
        self.calculate()
        return {
            "total_trades": self.total_trades,
            "winning_trades": self.winning_trades,
            "losing_trades": self.losing_trades,
            "win_rate": round(self.win_rate, 4),
            "total_pnl_pct": round(self.total_pnl_pct, 4),
            "avg_win_pct": round(self.avg_win, 4),
            "avg_loss_pct": round(self.avg_loss, 4),
            "profit_factor": round(self.profit_factor, 4),
            "sharpe_ratio": round(self.sharpe_ratio, 4),
            "max_drawdown_pct": round(self.max_drawdown, 4),
        }


class Backtester:
    """Run backtests on historical data."""

    def __init__(self, lookback_days: int = 365):
        self.lookback_days = lookback_days

    async def run(
        self,
        historical_events: list[dict],
        price_history: list[dict],
        ticker: str,
    ) -> BacktestResult:
        """
        Run a backtest using historical events and price data.

        Args:
            historical_events: List of events with {date, title, description, event_type, severity}
            price_history: List of price points with {date, close}
            ticker: The stock ticker symbol
        """
        result = BacktestResult()

        if not price_history or not historical_events:
            logger.warning("No historical data for backtest")
            return result

        price_by_date = {}
        for p in price_history:
            date_str = p.get("date", p.get("price_date", ""))
            if date_str:
                price_by_date[date_str[:10]] = p.get("close", p.get("close_price", 0))

        sorted_dates = sorted(price_by_date.keys())
        if not sorted_dates:
            return result

        for event in historical_events:
            event_date = str(event.get("date", event.get("event_date", "")))[:10]
            if event_date not in price_by_date:
                continue

            entry_price = price_by_date.get(event_date)
            if not entry_price:
                continue

            # Generate signal from historical event
            signal = generate_signal(
                impact=type('obj', (object,), {
                    'composite_risk': event.get("severity", 0.5) if isinstance(event.get("severity"), (int, float)) else 0.5,
                    'local_severity': event.get("severity", 0.5) if isinstance(event.get("severity"), (int, float)) else 0.5,
                    'entity_count': event.get("entity_count", 1),
                })(),
                market=None,
            )

            if signal.action == "HOLD":
                continue

            # Find exit date (look 5-20 trading days ahead)
            entry_idx = sorted_dates.index(event_date) if event_date in sorted_dates else -1
            if entry_idx == -1:
                continue

            # Exit after 10 trading days
            exit_idx = min(entry_idx + 10, len(sorted_dates) - 1)
            exit_date = sorted_dates[exit_idx]
            exit_price = price_by_date[exit_date]

            trade = BacktestTrade(
                signal=signal,
                entry_price=float(entry_price),
                entry_date=datetime.fromisoformat(event_date),
                exit_price=float(exit_price),
                exit_date=datetime.fromisoformat(exit_date),
            )
            trade.close(float(exit_price), datetime.fromisoformat(exit_date))
            result.trades.append(trade)

        result.calculate()
        logger.info(
            f"Backtest for {ticker}: {result.total_trades} trades, "
            f"win_rate={result.win_rate:.1%}, Sharpe={result.sharpe_ratio:.2f}"
        )
        return result
